apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argotest
  namespace: argotest
spec:
  project: default

  source:
    repoURL: https://github.com/acutchin-bitpusher/argotest
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: argotest

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

