apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argotest
  namespace: argotest
spec:
  project: default

  source:
    repoURL: git@github.com:BuiltTechnologies/built-bitpusher.git
    targetRevision: HEAD
    path: env/ac2/services/argotest/0.0.1
  destination: 
    server: https://kubernetes.default.svc
    namespace: argotest

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

